name: Create Emulator

on:
  push: # TODO remove this
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    name: Run Job

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      ACCESS_TOKEN: ${{ secrets.TOKEN }}
      ANDROID_VERSION: 34

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2.4.2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Test sdkmanager
        run: |
          sdkmanager --version

      - name: Installations
        run: |
          sdkmanager --version
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "platforms;android-34"
          sdkmanager --install "system-images;android-34;google_apis;x86_64"
          sdkmanager emulator
          ls
          sdkmanager --list_installed

      - name: Start Emulator
        run: |
          avdmanager create avd --force --name gha_emulator --device "pixel_6" --package "system-images;android-34;google_apis;x86_64"
          $ANDROID_HOME/emulator/emulator --help
