name: Create Emulator

on:
  push: # TODO remove this
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    name: Run Job

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      ACCESS_TOKEN: ${{ secrets.TOKEN }}
      ANDROID_VERSION: 34

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2.4.2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

#      - name: ls
#        run: ls -a
#
#      # TODO caching
#      - name: Get cli
#        run:  wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
#
#      - name: Unzip
#        run: unzip commandlinetools-linux-11076708_latest.zip -d sdk
#
#      - name: ls
#        run: ls sdk/cmdline-tools/bin
#
#      - name: update folders
#        run: |
#          mkdir sdk/latest
#          mv sdk/cmdline-tools/* sdk/latest
#          mv sdk/latest sdk/cmdline-tools
#          ls sdk/cmdline-tools
#
#      - name: Update Path
#        run: |
#          cd sdk
#          echo $PATH
#          export ANDROID_HOME="$(pwd)"
#          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
#          echo $PATH

#      - name: Test sdkmanager path
#        run: |
#          cd sdk
#          pwd
#          echo $ANDROID_HOME
#          ls -a
#          ls cmdline-tools
#          ./cmdline-tools/latest/bin/sdkmanager --version

      - name: Test sdkmanager
        run: |
          sdkmanager --version

      - name: Installations
        run: |
          sdkmanager --version
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "platforms;android-34"
          sdkmanager --install "system-images;android-34;google_apis;x86_64"
          sdkmanager emulator
          sdkmanager --list_installed
          avdmanager create avd --name gha_emulator --device "pixel_6" --package "system-images;android-34;google_apis;x86_64"

      - name: List Installed
        run: |
          sdkmanager --version
          sdkmanager --list_installed
          avdmanager list avd
