name: Espresso Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Run Tests

    runs-on: macos-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      ACCESS_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2.4.2

      # TODO fix emulator issues
      - id: list-devices
        run: avdmanager list device

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Create AVD and Generate Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Tests on Final Flavor
        timeout-minutes: 15
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedFinalDebugAndroidTest --info --stacktrace -PespressoRetries=3

      - name: Run Tests on Dev Flavor
        timeout-minutes: 20
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDevDebugAndroidTest --info --stacktrace -PespressoRetries=3

      # Steps
      # Install cmdline-tools
      # Add cmdline-tools/bin to PATH, or access cmdline-tools/bin/sdkmanager
      # TODO identify which install is needed
      # sdkmanager --sdk_root=~/cmdline-tools/ --install "platforms;android-VERSION"
      # sdkmanager --sdk_root=~/cmdline-tools/ --install "system-images;android-VERSION;google_apis;x86_64"
      # sdkmanager --sdk_root=~/cmdline-tools/ --install "system-images;android-VERSION;default;x86_64"
