name: Espresso Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      ACCESS_TOKEN: ${{ secrets.TOKEN }}
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Java Version
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-31

      - name: Create AVD and Generate Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: Galaxy Nexus
          cores: 2
          sdcard-path-or-size: 100M
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Run Tests on Final Flavor
        timeout-minutes: 15
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: Galaxy Nexus
          cores: 2
          ram-size: 2048M
          sdcard-path-or-size: 100M
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedFinalDebugAndroidTest --info --stacktrace -PespressoRetries=3

      - name: Run Tests on Dev Flavor
        if: false
        timeout-minutes: 20
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: Galaxy Nexus
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDevDebugAndroidTest --info --stacktrace -PespressoRetries=3
